In [1]:
import tensorflow as tf
import numpy as np

# Define the 5×5 input matrix
input_matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
], dtype=np.float32).reshape(1, 5, 5, 1)  # Reshaped to 4D for TensorFlow (batch, height, width, channels)

# Define the 3×3 kernel
kernel = np.array([
    [1, 0, -1],
    [1, 0, -1],
    [1, 0, -1]
], dtype=np.float32).reshape(3, 3, 1, 1)  # Reshaped for TensorFlow (height, width, in_channels, out_channels)

# Convert to TensorFlow tensors
input_tensor = tf.constant(input_matrix, dtype=tf.float32)
kernel_tensor = tf.constant(kernel, dtype=tf.float32)

# Perform convolution operations with different stride and padding
def perform_convolution(stride, padding):
    conv_layer = tf.nn.conv2d(input_tensor, kernel_tensor, strides=[1, stride, stride, 1], padding=padding)
    return conv_layer.numpy().squeeze()  # Convert tensor to NumPy and remove single dimensions

# Compute outputs
output_valid_stride_1 = perform_convolution(1, 'VALID')
output_same_stride_1 = perform_convolution(1, 'SAME')
output_valid_stride_2 = perform_convolution(2, 'VALID')
output_same_stride_2 = perform_convolution(2, 'SAME')

# Print the output feature maps
print("Output with Stride = 1, Padding = 'VALID':\n", output_valid_stride_1)
print("\nOutput with Stride = 1, Padding = 'SAME':\n", output_same_stride_1)
print("\nOutput with Stride = 2, Padding = 'VALID':\n", output_valid_stride_2)
print("\nOutput with Stride = 2, Padding = 'SAME':\n", output_same_stride_2)

Output with Stride = 1, Padding = 'VALID':
 [[-6. -6. -6.]
 [-6. -6. -6.]
 [-6. -6. -6.]]

Output with Stride = 1, Padding = 'SAME':
 [[ -9.  -4.  -4.  -4.  13.]
 [-21.  -6.  -6.  -6.  27.]
 [-36.  -6.  -6.  -6.  42.]
 [-51.  -6.  -6.  -6.  57.]
 [-39.  -4.  -4.  -4.  43.]]

Output with Stride = 2, Padding = 'VALID':
 [[-6. -6.]
 [-6. -6.]]

Output with Stride = 2, Padding = 'SAME':
 [[ -9.  -4.  13.]
 [-36.  -6.  42.]
 [-39.  -4.  43.]]
